//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//the code is regenerated. 
// </auto-generated>
//------------------------------------------------------------------------------

namespace kumaricinema
{
    public partial class MovieOccupancyPerformer
    {
 /// <summary>
 /// ddlMovies control.
 /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
    protected global::System.Web.UI.WebControls.DropDownList ddlMovies;

        /// <summary>
        /// SqlDataSourceMovies control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.SqlDataSource SqlDataSourceMovies;

        /// <summary>
        /// btnSearch control.
    /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.Button btnSearch;

        /// <summary>
      /// pnlMovieDetails control.
        /// </summary>
 /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.Panel pnlMovieDetails;

      /// <summary>
        /// fvMovieDetails control.
        /// </summary>
        /// <remarks>
      /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
     /// </remarks>
        protected global::System.Web.UI.WebControls.FormView fvMovieDetails;

        /// <summary>
        /// SqlDataSourceMovieDetails control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
 /// To modify move field declaration from designer file to code-behind file.
/// </remarks>
        protected global::System.Web.UI.WebControls.SqlDataSource SqlDataSourceMovieDetails;

        /// <summary>
     /// pnlTopPerformers control.
        /// </summary>
    /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.Panel pnlTopPerformers;

        /// <summary>
   /// lblResultMessage control.
        /// </summary>
   /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
   protected global::System.Web.UI.WebControls.Label lblResultMessage;

        /// <summary>
/// gvTopPerformers control.
    /// </summary>
   /// <remarks>
        /// Auto-generated field.
 /// To modify move field declaration from designer file to code-behind file.
    /// </remarks>
        protected global::System.Web.UI.WebControls.GridView gvTopPerformers;

        /// <summary>
        /// SqlDataSourceTopPerformers control.
        /// </summary>
 /// <remarks>
   /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
  /// </remarks>
      protected global::System.Web.UI.WebControls.SqlDataSource SqlDataSourceTopPerformers;

        /// <summary>
        /// pnlAllPerformers control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.Panel pnlAllPerformers;

        /// <summary>
        /// gvAllPerformers control.
        /// </summary>
        /// <remarks>
   /// Auto-generated field.
     /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
     protected global::System.Web.UI.WebControls.GridView gvAllPerformers;

     /// <summary>
     /// SqlDataSourceAllPerformers control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.SqlDataSource SqlDataSourceAllPerformers;

        /// <summary>
        /// pnlMovieStats control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
  protected global::System.Web.UI.WebControls.Panel pnlMovieStats;

        /// <summary>
      /// gvMovieStats control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
      /// </remarks>
        protected global::System.Web.UI.WebControls.GridView gvMovieStats;

        /// <summary>
  /// SqlDataSourceMovieStats control.
        /// </summary>
     /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
   protected global::System.Web.UI.WebControls.SqlDataSource SqlDataSourceMovieStats;
    }
}
