//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//  Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated. 
// </auto-generated>
//------------------------------------------------------------------------------

namespace kumaricinema
{
    public partial class TheaterCityHallMovie
    {
  /// <summary>
      /// ddlCity control.
        /// </summary>
        /// <remarks>
    /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
     /// </remarks>
        protected global::System.Web.UI.WebControls.DropDownList ddlCity;

/// <summary>
      /// SqlDataSourceCities control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
   /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
    protected global::System.Web.UI.WebControls.SqlDataSource SqlDataSourceCities;

        /// <summary>
        /// ddlTheatre control.
        /// </summary>
  /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
  protected global::System.Web.UI.WebControls.DropDownList ddlTheatre;

     /// <summary>
        /// SqlDataSourceTheatres control.
        /// </summary>
        /// <remarks>
 /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.SqlDataSource SqlDataSourceTheatres;

      /// <summary>
        /// ddlHall control.
        /// </summary>
    /// <remarks>
        /// Auto-generated field.
 /// To modify move field declaration from designer file to code-behind file.
/// </remarks>
        protected global::System.Web.UI.WebControls.DropDownList ddlHall;

        /// <summary>
        /// SqlDataSourceHalls control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
protected global::System.Web.UI.WebControls.SqlDataSource SqlDataSourceHalls;

   /// <summary>
        /// btnSearch control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
   /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.Button btnSearch;

        /// <summary>
        /// pnlTheatreDetails control.
     /// </summary>
  /// <remarks>
     /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
/// </remarks>
   protected global::System.Web.UI.WebControls.Panel pnlTheatreDetails;

        /// <summary>
    /// fvTheatreDetails control.
        /// </summary>
        /// <remarks>
    /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
     protected global::System.Web.UI.WebControls.FormView fvTheatreDetails;

        /// <summary>
/// SqlDataSourceTheatreDetails control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
      /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.SqlDataSource SqlDataSourceTheatreDetails;

        /// <summary>
        /// pnlHallDetails control.
        /// </summary>
        /// <remarks>
/// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
    protected global::System.Web.UI.WebControls.Panel pnlHallDetails;

        /// <summary>
        /// gvHallDetails control.
  /// </summary>
     /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.GridView gvHallDetails;

        /// <summary>
        /// SqlDataSourceHallDetails control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.SqlDataSource SqlDataSourceHallDetails;

        /// <summary>
        /// pnlMovieShowtime control.
        /// </summary>
    /// <remarks>
      /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.Panel pnlMovieShowtime;

        /// <summary>
   /// lblResultCount control.
     /// </summary>
        /// <remarks>
  /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
     protected global::System.Web.UI.WebControls.Label lblResultCount;

      /// <summary>
    /// gvMovieShowtime control.
        /// </summary>
        /// <remarks>
     /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.GridView gvMovieShowtime;

    /// <summary>
     /// SqlDataSourceMovieShowtime control.
      /// </summary>
 /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
protected global::System.Web.UI.WebControls.SqlDataSource SqlDataSourceMovieShowtime;

     /// <summary>
 /// pnlMovieSummary control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
    protected global::System.Web.UI.WebControls.Panel pnlMovieSummary;

      /// <summary>
        /// gvMovieSummary control.
        /// </summary>
    /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.GridView gvMovieSummary;

        /// <summary>
        /// SqlDataSourceMovieSummary control.
   /// </summary>
    /// <remarks>
     /// Auto-generated field.
      /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
    protected global::System.Web.UI.WebControls.SqlDataSource SqlDataSourceMovieSummary;
    }
}
