//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
// Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated. 
// </auto-generated>
//------------------------------------------------------------------------------

namespace kumaricinema
{


    public partial class UserTicket
    {

        /// <summary>
        /// ddlUsers control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.DropDownList ddlUsers;

        /// <summary>
        /// SqlDataSourceUsers control.
        /// </summary>
    /// <remarks>
 /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
   protected global::System.Web.UI.WebControls.SqlDataSource SqlDataSourceUsers;

  /// <summary>
      /// pnlUserDetails control.
  /// </summary>
 /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
   protected global::System.Web.UI.WebControls.Panel pnlUserDetails;

        /// <summary>
        /// fvUserDetails control.
        /// </summary>
        /// <remarks>
     /// Auto-generated field.
  /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.FormView fvUserDetails;

        /// <summary>
        /// SqlDataSourceUserDetails control.
  /// </summary>
      /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
 /// </remarks>
    protected global::System.Web.UI.WebControls.SqlDataSource SqlDataSourceUserDetails;

        /// <summary>
        /// pnlTickets control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
     /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.Panel pnlTickets;

        /// <summary>
        /// lblTicketCount control.
 /// </summary>
      /// <remarks>
    /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.Label lblTicketCount;

        /// <summary>
        /// gvUserTickets control.
        /// </summary>
        /// <remarks>
     /// Auto-generated field.
   /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.GridView gvUserTickets;

        /// <summary>
        /// SqlDataSourceUserTickets control.
        /// </summary>
   /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.SqlDataSource SqlDataSourceUserTickets;

   /// <summary>
     /// pnlSummary control.
      /// </summary>
      /// <remarks>
        /// Auto-generated field.
     /// To modify move field declaration from designer file to code-behind file.
    /// </remarks>
        protected global::System.Web.UI.WebControls.Panel pnlSummary;

        /// <summary>
        /// gvSummary control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
      /// </remarks>
        protected global::System.Web.UI.WebControls.GridView gvSummary;

 /// <summary>
        /// SqlDataSourceSummary control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.SqlDataSource SqlDataSourceSummary;
    }
}
